name: 'Tofu init'
description: 'Init tofu (terraform) manifest with custom backend section'
author: 'sidlen'
inputs:
  manifest_path:
    description: 'Realative path to directory with tofu (terraform) manifests files, default - workspace directory'
    required: false
    default: "${{ env.TOFU_MANIFEST_DIR }}"
  backend_type:
    description: 'Where to store tofu (terraform) state, use: s3 or consul '
    required: false
    default: "consul"
  s3_address:
    description: 'S3 server address'
    required: false
    default: "${{ env.S3_ADDRESS }}"
  s3_bucket:
    description: 'S3 bucket name (required if backend_type is s3)'
    required: false
    default: 'opentofu-states'
  s3_path:
    description: 'Path in S3 bucket (required if backend_type is s3)'
    required: false
    default: "${{ github.repository }}/${{ env.ENVIRONMENT }}"
  s3_key:
    description: 'S3 access key (required if backend_type is s3)'
    required: false
    default: "${{ vars.S3_ACCESS_KEY }}"
  s3_secret:
    description: 'S3 secret key (required if backend_type is s3)'
    required: false
    default: "${{ secrets.S3_SECRET_KEY }}"
  consul_address:
    description: 'Consul server address'
    required: false
    default: "${{ env.CONSUL_ADDRESS }}"
  consul_scheme:
    description: 'Specifies what protocol to use when talking to the given consul_address, either http or https'
    required: false
    default: 'https'
  consul_token:
    description: 'Consul access token with rw rights'
    required: false
    default: "${{ secrets.CONSUL_TOKEN }}"
  consul_path:
    description: 'Consul KV path to store state'
    required: false
    default: "${{ github.repository }}/${{ env.ENVIRONMENT }}"
runs:
  using: 'composite'
  steps:
    - name: Set environment variables from inputs.backend_type
      shell: bash
      run: |
        export MANIFEST_DIR="${{ gitea.workspace }}"/"${{ inputs.manifest_path }}"
        if [[ "${{ inputs.backend_type }}" == consul ]]; then
          export TF_CONSUL_ADDRESS="${{ inputs.consul_address }}"
          export TF_CONSUL_SCHEME="${{ inputs.consul_scheme }}"
          export TF_ACCESS_TOKEN="${{ inputs.consul_token }}"
          export TF_PATH="${{ inputs.consul_path }}"
        elif [[ "${{ inputs.backend_type }}" == s3 ]]; then
          export TF_S3_ADDRESS="${{ inputs.s3_address }}"
          export TF_BUCKET="${{ inputs.s3_bucket }}"
          export TF_KEY="${{ inputs.s3_path }}"
          export TF_ACCESS_KEY="${{ inputs.s3_key }}"
          export TF_SECRET_KEY="${{ inputs.s3_secret }}"
        fi
        chmod +x "${{ gitea.action_path }}"/"${{ inputs.backend_type }}"-terraform-init.sh
        "${{ gitea.action_path }}"/"${{ inputs.backend_type }}"-terraform-init.sh
