name: 'Tofu import'
description: 'Import existing resources into the Tofu (terraform) state based on manifest'
author: 'sidlen'
inputs:
  manifest_path:
    description: 'Realative path to directory with tofu (terraform) manifests files'
    required: false
    default: "${{ env.TOFU_MANIFEST_DIR }}"
  plan_json:
    description: 'Saved plan.json file from plan action'
    required: true
    default: "plan.json"

runs:
  using: 'composite'
  steps:
    - name: Generate import commands
      id: import_commands
      uses: https://github.com/sidlen/actions-opentofu/import_commands@v1.2.0-dev-07
      env:
        manifest_path: "${{ inputs.manifest_path }}"
        plan_json: "${{ inputs.plan_json }}"
    - name: DEBUG show imports script
      shell: bash
      run: cat import_commands.sh
    - name: DEBUG
      run: ls -l
      shell: bash
    - name: Run import commands
      shell: bash
      run: |
        chmod +x import-commands.sh
        ./import-commands.sh
