name: 'Tofu import'
description: 'Import existing resources into the Tofu (terraform) state based on manifest'
author: 'sidlen'
inputs:
  manifest_path:
    description: 'Realative path to directory with tofu (terraform) manifests files'
    required: false
    default: "${{ env.TOFU_MANIFEST_DIR }}"
  plan_json:
    description: 'Saved plan.json file from plan action'
    required: true
    default: "plan.json"

runs:
  using: 'composite'
  steps:
    - name: Tofu import
      run: |
        chmod +x "${{ gitea.action_path }}"/generate_import.sh
        "${{ gitea.action_path }}"/generate_import.sh
      shell: bash
      env:
        TF_VAR_OWNER: "${{ gitea.actor }}"
        TOFU_MANIFEST_DIR: "${{ inputs.manifest_path }}"
        TOFU_WORKSPACE: "${{ gitea.workspace }}"
