name: 'Tofu validate'
description: 'Validate .tf files'
author: 'sidlen'
inputs:
  manifest_path:
    description: 'Realative path to directory with tofu (terraform) manifests (.tf) files, default - workspace directory'
    required: false
    default: "${{ env.TOFU_MANIFEST_DIR }}"
runs:
  using: 'composite'
  steps:
    - name: Tofu validate
      run: tofu -chdir="${{ gitea.workspace }}"/"${{ inputs.manifest_path }}" validate
      shell: bash
