name: 'Tofu sync state'
description: 'Sync tofu (terraform) state with manifest and plan changes.'
author: 'sidlen'
inputs:
  backend_type:
    description: 'Where to store tofu (terraform) state, use: s3 or consul '
    required: false
    default: "consul"
  s3_address:
    description: 'S3 server address'
    required: false
    default: "${{ env.S3_ADDRESS }}"
  s3_scheme:
    description: 'Specifies what protocol to use when talking to the given s3_address, either http or https'
    required: false
    default: 'https'
  s3_bucket:
    description: 'S3 bucket name (required if backend_type is s3)'
    required: false
    default: 'opentofu-states'
  s3_path:
    description: 'Path in S3 bucket (required if backend_type is s3)'
    required: false
    default: "${{ github.repository }}/${{ env.ENVIRONMENT }}"
  s3_key:
    description: 'S3 access key (required if backend_type is s3)'
    required: false
    default: "${{ vars.S3_ACCESS_KEY }}"
  s3_secret:
    description: 'S3 secret key (required if backend_type is s3)'
    required: false
    default: "${{ secrets.S3_SECRET_KEY }}"
  consul_address:
    description: 'Consul server address'
    required: false
    default: "${{ env.CONSUL_ADDRESS }}"
  consul_scheme:
    description: 'Specifies what protocol to use when talking to the given consul_address, either http or https'
    required: false
    default: 'https'
  consul_token:
    description: 'Consul access token with rw rights'
    required: false
    default: "${{ secrets.CONSUL_TOKEN }}"
  consul_path:
    description: 'Consul KV path to store state'
    required: false
    default: "${{ github.repository }}/${{ env.ENVIRONMENT }}"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TF_CONSUL_ADDRESS: "${{ inputs.consul_address }}"
    TF_CONSUL_SCHEME: "${{ inputs.consul_scheme }}"
    TF_ACCESS_TOKEN: "${{ inputs.consul_token }}"
    TF_PATH: "${{ inputs.consul_path }}"
    TF_S3_ADDRESS: "${{ inputs.s3_address }}"
    TF_S3_SCHEME: "${{ inputs.s3_scheme }}"
    TF_BUCKET: "${{ inputs.s3_bucket }}"
    TF_KEY: "${{ inputs.s3_path }}"
    TF_ACCESS_KEY: "${{ inputs.s3_key }}"
    TF_SECRET_KEY: "${{ inputs.s3_secret }}"
outputs:
  log:
    description: 'Log of changes in state'
