name: 'Install OpenTofu'
description: 'Downloads and installs OpenTofu'
author: 'sidlen'
inputs:
  version:
    description: 'Version of OpenTofu to install'
    required: false
    default: '1.6.2'
runs:
  using: 'composite'
  steps:
    - name: Download OpenTofu install script
      run: wget --secure-protocol=TLSv1_2 --https-only https://get.opentofu.org/install-opentofu.sh -O install-opentofu.sh
      shell: bash

    - name: Make script executable
      run: chmod +x install-opentofu.sh
      shell: bash

    - name: Install OpenTofu
      run: ./install-opentofu.sh --install-method standalone --opentofu-version ${{ inputs.version }}
      shell: bash